version: '3.8'
services:

# ----------------------------------------------
# mysql 5.7 : container creation 
# ----------------------------------------------
 mysql:
  image: mysql:5.7
  hostname: mysql
  container_name: 'mysql'
  environment:
      MYSQL_ROOT_PASSWORD: passwordtochange01
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: passwordtochange02
  links:
   - debian
  depends_on:
   - debian
  tty: true
  networks:
     - lab
  restart: 'always'
  ports:
   - '3306:3306' 
  volumes:
   - /lab/projet01/docker-data/data-mysql/db:/var/lib/mysql  
   - /lab/projet01/docker-data/data-shared:/opt   


# ----------------------------------------------
# wordpress 5 : container creation 
# ----------------------------------------------
 wordpress:
  image: wordpress:latest
  hostname: wordpress
  container_name: 'wordpress'
  links:
   - mysql
  depends_on:
      - mysql
  tty: true
  networks:
     - lab
  restart: always
  ports:
    - '8000:80'
  environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: passwordtochange02
      WORDPRESS_DB_NAME: wordpress
  volumes:
   - /lab/projet01/docker-data/data-wordpress/myblogfr:/var/www/html  
   - /lab/projet01/docker-data/data-shared:/opt   


# ----------------------------------------------
# networks
# ----------------------------------------------
networks:
   lab:
      driver: bridge
